---
- name: Add PaperCut Site
  template:
    src: paper.conf
    dest: /etc/nginx/sites-available/paper.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - nginx

- name: Enable paper site
  file:
    src: ../sites-available/paper.conf
    dest: /etc/nginx/sites-enabled/paper.conf
    state: link
  notify:
    - nginx

- name: Install firewall rules
  copy:
    src: paper.rules
    dest: /etc/iptables.d/
    owner: root
    group: root
    mode: 0640
  notify:
  - iptables
