---
- name: Copy znapdragon script
  copy:
    src: znapdragon/znapdragon
    dest: /usr/local/sbin/znapdragon
    owner: root
    group: root
    mode: 0500
  when: inventory_hostname == groups['nas'][0]

- name: Copy crontab
  copy:
    src: zfs-management.cron
    dest: /etc/cron.d/zfs-management
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname == groups['nas'][0]

- name: Copy mkhomes
  copy:
    src: mkhomes
    dest: /usr/local/sbin/mkhomes
    owner: root
    group: root
    mode: 0500

- name: Create mkhomes service directory
  file:
    path: /etc/sv/mkhomes
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy mkhomes run script
  copy:
    src: mkhomes_listener
    dest: /etc/sv/mkhomes/run
    owner: root
    group: root
    mode: 0755


- name: Set root ZFS properties
  zfs:
    name: tank
    state: present
    checksum: sha256
    compression: lz4
    atime: off

- name: Set /srv/ ZFS properties
  zfs:
    name: tank/srv
    state: present
    mountpoint: /srv
    canmount: off
    exec: off
    setuid: off

- name: Set /archives/ ZFS properties
  zfs:
    name: tank/archives
    state: present
    canmount: off
    exec: off
    setuid: off

- name: Make propertyless children
  zfs:
    name: tank/{{ item }}
    state: present
  with_items:
    - srv/homes
    - srv/warpdrive
    - srv/ydrive

- include: ydrive_dirs.yml

- name: Install firewall rules
  copy:
    src: nas.rules
    dest: /etc/iptables.d/nas.rules
    owner: root
    group: root
    mode: 0640
  notify:
    - iptables

- name: Install daemons
  xbps:
    pkg:
      - nfs-utils
      - rsync
      - openbsd-netcat
    state: present

- name: Create /etc/conf.d
  file:
    path: /etc/conf.d/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Install nfs-server.conf
  copy:
    src: nfs-server.conf
    dest: /etc/conf.d/nfs-server.conf
    owner: root
    group: root
    mode: 0644

- name: Enable services
  file:
    src: /etc/sv/{{ item }}
    dest: /var/service/{{ item }}
    state: link
  with_items:
    - rpcbind
    - statd
    - nfs-server
    - rsyncd
    - mkhomes
