---
- name: Install dependencies
  xbps:
    pkg:
      - python-pip
      - git-all
    state: present

- name: Install firewall rules
  copy:
    src: cvdoc.rules
    dest: /etc/iptables.d/cvdoc.rules
    owner: root
    group: root
    mode: 0640
  notify:
    - iptables

- name: Install mkdocs
  pip:
    name: mkdocs
    state: present

- name: Create site folder
  file:
    path: /var/www/cvdoc
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Install mkdocs_build.sh
  template:
    src: mkdocs_build.sh
    dest: /usr/local/sbin/mkdocs-build-{{ mkdocs_site_name }}
    owner: root
    group: root
    mode: 0755

- name: Install mkdocs cronjob
  template:
    src: mkdocs_build.cron
    dest: /etc/cron.d/mkdocs_build
    owner: root
    group: root
    mode: 0644

- name: Copy Site descriptor
  copy:
    src: cvdoc.conf
    dest: /etc/nginx/sites-available/cvdoc.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - nginx

- name: Enable Site
  file:
    src: ../sites-available/cvdoc.conf
    dest: /etc/nginx/sites-enabled/cvdoc.conf
    state: link
  notify:
    - nginx
